### ISSUE TITLE
Move testMethods to dedicated class

### ISSUE THREAD

**Issue by gostrc** [neowit/apexmock#7]
This isn't required, but it's good practice.

Especially since salesforce now requires this in classes with newer metadata types.

Affected files:
MockUtils.cls

**Comment by neowit** [comment]
Hi @gostrc 

Thank you for the suggestion.

To be honest, I do not see a real value in creating a separate file for few test methods which fit in one screen. 

With regard to this being a good practice - when apex is updated to support packages and/or separate test class file location from main classes (like all real programming languages do), then keeping tests separate from main logic will be a good idea for any test. Until then I am not certain that it is.

Happy to hear a counter-argument with alternative reasoning.

**Comment by gostrc** [comment]
Other than the "good practice" argument, there is the fact that you will not be able to bump up the api version of MockUtils.cls past 27.0. Other than that, I can't think of any good reason why you should switch.

This ticket is more of a judgement call on your part since there isn't an actual problem with the current code. Feel free to close it if you decide to keep MockUtil as is.

**Comment by neowit** [comment]
Thanks for your thoughts.
I guess when there will be a need to update MockUtils with some new functionality requiring API > v27, or MockUtils gets changed and needs more tests, then the subject of extracting tests from it can be re-visited.
